name: ${project.artifactId}
version: ${project.version}
main: com.acpsoldier.acpfood.AcpFood
commands:
  acpfood:
    description: Type this command to see the version of Acp Food this server is running.
permissions:
  acpfood.other.refill:
    description: Players with this permission can auto-refill food.
  acpfood.foods.*:
    description: Players with this permission can eat all foods.
  acpfood.foods.cannedbeans:
    description: Players with this permission can eat Canned Beans.
  acpfood.foods.cannedpasta:
    description: Players with this permission can eat Canned Pasta.
  acpfood.foods.cannedfish:
    description: Players with this permission can eat Canned Fish.
  acpfood.foods.mountaindew:
    description: Players with this permission can drink Mountain Dew.
  acpfood.foods.pepsi:
    description: Players with this permission can drink Pepsi.
  acpfood.foods.sugar:
    description: Players with this permission can eat Sugar.
  acpfood.foods.goldenapple:
    description: Players with this permission can eat Sugar.